### PR TITLE
create specific galaxy client http error exception

### PR DESCRIPTION
**Pull request by chr-stian**

### CODE REVIEW

**Comment by hendersonreed** [comment]
Do we need two custom error types? I'm not seeing the value in differentiating between a client http error that's thrown in client.py and one that's thrown by the wait_for_task function in utils.py.

**Comment by chr-stian** [comment]
@hendersonreed for RBAC testing I need to verify http error codes like this
`    with pytest.raises(GalaxyClientHttpError) as ctx:
        gc.create_role(role_name, 'any_description', permissions)
    assert ctx.value.http_error_codes == 403`

I believe there is no easy way to do this with GalaxyClientError.
I would say the exception thrown by wait_for_task is of a different kind. Let me know what you would do.

**Comment by hendersonreed** [comment]
I think they are the same type of error (both HTTP errors - in `wait_for_task` we're checking if the response is 500 because of intermittent server errors when checking task status.)

Did the code snippet you posted not work with the GalaxyClientError exception type? Maybe the solution is to consolidate our changes into the GalaxyClientError by inheriting from `requests.HTTPError` (which is what these error should actually be, since they're getting thrown when we make http requests.

**Comment by chr-stian** [comment]
you're absolutely right, changing it back but if you don't mind I'm keeping the else part

**Pull request closed without merging**
