### PR TITLE
galaxykit task list/wait: wait for a specific task, or any running/waiting tasks

### PR DESCRIPTION
**Pull request by himdel**
`galaxykit task wait all` - waits for any waiting running tasks to complete
`galaxykit task wait <uuid or href>` - wait for a specific task to complete, fail if the final state is not `completed`
`galaxykit task list` - list tasks
`galaxykit task list --only_running` - list waiting/running tasks

Fixes [AAH-1437](https://issues.redhat.com/browse/AAH-1437)

### CODE REVIEW

**Comment by hendersonreed** [comment]
I like this! This should replace some code we have in the IQE test suite as well, so that's great.

**Comment by MilanPospisil** [comment]
> I like this! This should replace some code we have in the IQE test suite as well, so that's great.

Yeah, I agree, we can add waiting for the tasks at the end of any galaxykit command sequences in tests and it will work without changing any of the codes :-)

**Comment by MilanPospisil** [comment]
It throws sporadic falures sometimes. I have bash scripts that repeatedly creates 50 collections and then deletes them. Then I called in second terminal repeatedly this command:
galaxykit -u admin -p admin task list --only_running

It occasionaly shows no running task or one (that is correct), but sometimes it throws error:

Traceback (most recent call last):
  File "/home/milan/.local/bin/galaxykit", line 33, in <module>
    sys.exit(load_entry_point('galaxykit', 'console_scripts', 'galaxykit')())
  File "/home/milan/software/galaxykit/galaxykit/command.py", line 676, in main
    print(format_list(resp["results"], "name"))
KeyError: 'results'

**Comment by hendersonreed** [comment]
I was reviewing another PR, https://github.com/ansible/galaxykit/pull/54 and it has some code that duplicates this work - I think we should ideally rely on this work, since it is more comprehensive. But it's something to consider, since we should consolidate all code related to tasks.

**Comment by himdel** [comment]
Reproduced the issue with...

```
 for n in {1..50}; do galaxykit collection delete foo bar$n ; done 
 for n in {1..50}; do galaxykit collection upload foo bar$n ; done 
 for n in {1..50}; do galaxykit -u admin -p admin task list --only_running ; done
```

(in 3 separate terminals)

---

The collection delete bit seems to keep failing with

```
Traceback (most recent call last):
  File "/home/himdel/.local/bin/galaxykit", line 33, in <module>
    sys.exit(load_entry_point('galaxykit', 'console_scripts', 'galaxykit')())
  File "/home/himdel/galaxykit/galaxykit/command.py", line 809, in main
    resp = collections.delete_collection(
  File "/home/himdel/galaxykit/galaxykit/collections.py", line 202, in delete_collection
    wait_for_task(client, resp)
  File "/home/himdel/galaxykit/galaxykit/utils.py", line 38, in wait_for_task
    if resp["state"] == "failed":
KeyError: 'state'
```

The collection upload occasionally fails with

```
Traceback (most recent call last):
  File "/home/himdel/.local/bin/galaxykit", line 33, in <module>
    sys.exit(load_entry_point('galaxykit', 'console_scripts', 'galaxykit')())
  File "/home/himdel/galaxykit/galaxykit/command.py", line 781, in main
    artifact = collections.upload_test_collection(
  File "/home/himdel/galaxykit/galaxykit/collections.py", line 45, in upload_test_collection
    upload_resp_url = upload_artifact(config, client, artifact)["task"]
  File "/home/himdel/galaxykit/galaxykit/collections.py", line 153, in upload_artifact
    resp = client._http("post", n_url, data=data, headers=headers)
  File "/home/himdel/galaxykit/galaxykit/client.py", line 190, in _http
    raise GalaxyClientError(*json["errors"])
galaxykit.utils.GalaxyClientError: {'status': '403', 'code': 'authentication_failed', 'title': 'Incorrect authentication credentials.', 'detail': 'Invalid token.'}
```

And task list is ocassionally failing with the aforementioned

```
Traceback (most recent call last):
  File "/home/himdel/.local/bin/galaxykit", line 33, in <module>
    sys.exit(load_entry_point('galaxykit', 'console_scripts', 'galaxykit')())
  File "/home/himdel/galaxykit/galaxykit/command.py", line 762, in main
    print(format_list(resp["results"], "name"))
KeyError: 'results'
```

**Comment by himdel** [comment]
.. but the reason for the task list failure is always that the response was just `{'detail': 'Invalid token.'}`.
and the same happens for the deletion errors.

So, I think this works as intended, but running multiple galaxykit commands at the same time can fail by fighting for tokens.

---

(still need to address Henderson's feedback, and looks like deletion waiting for task by default (#53) is slowing down multi-deletion to a crawl so we need to parametrize it)

**Comment by MilanPospisil** [comment]
> .. but the reason for the task list failure is always that the response was just `{'detail': 'Invalid token.'}`. and the same happens for the deletion errors.
> 
> So, I think this works as intended, but running multiple galaxykit commands at the same time can fail by fighting for tokens.
> 
> (still need to address Henderson's feedback, and looks like deletion waiting for task by default (#53) is slowing down multi-deletion to a crawl so we need to parametrize it)

So lets disscuss it in tuesday meeting, I will wait with the review.

**Review by chr-stian — APPROVED** [review]

**Comment by himdel** [comment]
Merged, we'll address the wait_task vs wait_for_task duplication in a separate PR.

@chr-stian do you know where (if anywhere) `wait_for_task` is used outside this repo please? Do we rely on any specific exceptions and behaviour already, or is this just used by `collection.py` now?

Also, what's the plan with waiting? I noticed that couple of deletion commands now wait for the task before finishing.
Is the plan to wait for any action to fully finish in galaxykit before exiting? Would it make sense to make such waiting optional (say, a `--wait` param, or maybe defalt to waiting and add a `--no-wait` param)?

**Comment by hendersonreed** [comment]
@himdel Not all actions come with task IDs, but I think we should probably implement your suggestion of adding a --no-wait parameter and waiting by default on all tasks that do provide a task id.

Regarding your other question about usage of `wait_for_task` outside this repo, I think the only place it's used is in our IQE test suite (as we update those tests, they will begin to use it more - at the moment there's only one use.)

**Pull request merged**
