### PR TITLE
Fixes for backup and restore

### PR DESCRIPTION
**Pull request by brahmanim**
- Update Collections Upload command
- Add Collections Move command.

### CODE REVIEW

**Comment by brahmanim** [comment]
@hendersonreed, I added a few additional corrections,
Please check if that PR can be merged and create a new release,
so I can use it on Jenkins pipelines.

**Review by hendersonreed — CHANGES_REQUESTED** [review]
These changes all look reasonable, but there are a lot of formatting changes - when I run `black` against this branch locally a lot of them get reverted.

Seems like there might be a line-length limit difference between our environments? A lot of the formatting changes I'm seeing are reverting the changes that take one long-line and turn it into a multi-line expression.

**Comment by brahmanim** [comment]
I have black rev: 21.11b1, in my environment.
What is your suggestion?
Could we just accept the black changes on long lines?

**Comment by hendersonreed** [comment]
If we accept the black changes, then the next time I change those files and commit, then we'll see the changes reverted. Let me see if I have something that's configuring black to allow long-lines. You might also see if you have configured black to have a particular max-line-length?

**Comment by hendersonreed** [comment]
Yep, I found it - all my fault :(

I've resolved it, and running `black` on the repo locally doesn't change anything, so this is perfect. I'm going to do a quick check that the new commands work as expected and if so then we'll merge and get a release out!

**Review by hendersonreed — DISMISSED** [review]

**Comment by hendersonreed** [comment]
@brahmanim I pulled these changes and noted a few small bugs I had introduced when we first hacked together this new command, so I fixed them - please check out these last two commits and let me know what you think.

**Comment by brahmanim** [comment]
Hi @hendersonreed,
Nice catch of the bug, I didn't check the move command with only 2 params of namespace and name!
Your correction is working now!
In addition to that, I found another issue, with the move_collection method,
The dest_url that we used for checking the collection move, includes filters,
In that case, if the collection doesn't found, the API will return empty metadata, with count=0,
And no exception will be thrown!
So I change the dest_url to use another API that is subtle for our case.
I also remove a leftover breakpoint.
Please review my last commit and let me know if this PR can be merged.

**Comment by hendersonreed** [comment]
That's a tricky bug! At one point I was able to trigger that exception I think (not sure why now) but this looks like a better API regardless!

Also, good catch on the stray breakpoint (I really ought to configure git to prevent me committing if I have one of those in the code still.)

Going to pull these changes and check them out in a bit. If they work, I'll merge and cut a release.

Great teamwork on this! Thanks for your help :smile:

**Comment by hendersonreed** [comment]
Yep, this is working as expected - merging and will put up a release PR

**Review by hendersonreed — APPROVED** [review]

**Pull request merged**
